/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as GuessTheCharacterIndexRouteImport } from './routes/guess-the-character/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuessTheCharacterIndexRoute = GuessTheCharacterIndexRouteImport.update({
  id: '/guess-the-character/',
  path: '/guess-the-character/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/guess-the-character/': typeof GuessTheCharacterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters': typeof CharactersIndexRoute
  '/guess-the-character': typeof GuessTheCharacterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/guess-the-character/': typeof GuessTheCharacterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/characters/' | '/guess-the-character/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/characters' | '/guess-the-character'
  id: '__root__' | '/' | '/characters/' | '/guess-the-character/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  GuessTheCharacterIndexRoute: typeof GuessTheCharacterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guess-the-character/': {
      id: '/guess-the-character/'
      path: '/guess-the-character'
      fullPath: '/guess-the-character/'
      preLoaderRoute: typeof GuessTheCharacterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  GuessTheCharacterIndexRoute: GuessTheCharacterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
